export const SEARCH_TRACKS = "SEARCH_TRACKS";
export const SEARCH_QUERY = "SEARCH_QUERY";
export const QUEUE_TRACK = "QUEUE_TRACK";
export const UPDATE_CURRENT_TRACK = "UPDATE_CURRENT_TRACK";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_PRIVATE_ID = "SET_PRIVATE_ID";
export const DISPLAY_CURRENT_TRACK = "DISPLAY_CURRENT_TRACK";
export const GET_ALL_USERS = "GET_ALL_USERS";
